//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int CalisID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public int DepartmanID { get; set; }
        public string TelefonNo { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
    }
}
