//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yonetici()
        {
            this.Departmanlars = new HashSet<Departmanlar>();
            this.Departmanlars1 = new HashSet<Departmanlar>();
        }
    
        public int YoneticiID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public int DepartmanID { get; set; }
        public string TelefonNo { get; set; }
        public string Sifre { get; set; }
        public string GizliSoru { get; set; }
        public string GizliCevap { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departmanlar> Departmanlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departmanlar> Departmanlars1 { get; set; }
        public virtual Departmanlar Departmanlar { get; set; }
    }
}
